People and Address entity
Eureka-Shoulders/nest-seed pull request #28
Opened 2022-01-06 12:43 UTC by devzgabriel

2022-01-08 15:18 UTC, SampaioLeal requested changes

2022-01-08 15:18 UTC, SampaioLeal commented on prisma/schema.prisma
> +  address  Address[]
```suggestion
  addresses  Address[]
```

2022-01-08 15:18 UTC, SampaioLeal commented on prisma/schema.prisma
> +  cpf  String
```suggestion
  identifier  String
```

2022-01-08 15:18 UTC, SampaioLeal commented on prisma/schema.prisma
> +  cep          String
```suggestion
  zipcode          String
```

2022-01-08 15:25 UTC, JoaoptGaino commented on prisma/seed.ts
> +  const people = [
Don't forget to change 'cpf' to 'identifier' here in the seed too.

2022-01-10 19:41 UTC, SampaioLeal approved these changes

2022-01-10 19:43 UTC, merged